{
  "type": "record",
  "name": "EventoAsignacionAceptadaPorReglaPartner",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "time",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "name": "ingestion",
      "type": [
        "null",
        "long"
      ]
    },
    {
      "name": "specversion",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "type",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "datacontenttype",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "service_name",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "correlation_id",
      "type": [
        "null",
        "string"
      ]
    },
    {
      "name": "data",
      "type": [
        "null",
        {
          "type": "record",
          "name": "AsignacionAceptadaPorReglaPartnerPayload",
          "fields": [
            {
              "name": "trabajo_id",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "asignacion_id",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "proveedor_id",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "partner_id",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "regla_version",
              "type": [
                "null",
                "int"
              ]
            },
            {
              "name": "motivo",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "verificado_en",
              "type": [
                "null",
                "long"
              ]
            }
          ]
        }
      ]
    }
  ]
}
