"""Puerto de persistencia del agregado Proveedor."""
from abc import ABC, abstractmethod
from uuid import UUID


class RepositorioProveedores(ABC):
    @abstractmethod
    def obtener_por_id(self, id: UUID): ...
    @abstractmethod
    def obtener_todos(self) -> list: ...
    @abstractmethod
    def obtener_por_estado(self, estado: str) -> list: ...
    @abstractmethod
    def agregar(self, proveedor): ...
    @abstractmethod
    def actualizar(self, proveedor): ...
    @abstractmethod
    def eliminar(self, id: UUID): ...
